[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  # Production environment variables will be set in Netlify dashboard
  NODE_ENV = "production"

[context.deploy-preview.environment]
  # Deploy preview environment
  NODE_ENV = "development"